service: tile-broker-lambda
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:ListObjects
      Resource: "arn:aws:s3:::image-tile-mart/*"

functions:
  app:
    handler: index.handler
    environment:
      S3_BUCKET: image-tile-mart
      S3_PATH_TILE_CACHE: tile-cache
      S3_PATH_STYLE_CONFIG: style-config
      RENDER_URL: https://lc2l48p06k.execute-api.us-east-1.amazonaws.com/dev/tiles
    events:
      - http:
          path: /
          method: any
          cors: true


  fetchTile:
    handler: index.handler
    environment:
      S3_BUCKET: image-tile-mart
      S3_PATH_TILE_CACHE: tile-cache
      S3_PATH_STYLE_CONFIG: style-config
      RENDER_URL: https://lc2l48p06k.execute-api.us-east-1.amazonaws.com/dev/tiles
    events:
      - http:
          path: /tiles/{proxy+}
          method: get
          cors: true